volumes:
  mysql_data_vol:
  mysql_log:

services:
  nginx:
    image: nginx:1.25-alpine
    profiles: ['nginx']
    command: /bin/sh -c "envsubst '$$NODE_PROXY_PORT'< /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 127.0.0.1:${NGINX_HTTP_PORT:-80}:80
    volumes:
      - ./infra/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf.template
      - ./client/dist:/usr/share/nginx/html:ro
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - NODE_PROXY_PORT=${APP_PORT}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '1'

  db:
    image: mysql:8.0
    command: bash -c '[ -n "${USER_UID}" ] && usermod -o -u ${USER_UID} mysql; [ -n "${USER_GID}" ] && groupmod -o -g ${USER_GID} mysql; chown -R mysql:root /var/run/mysqld/ /var/log/mysql/ /var/lib/mysql/; /entrypoint.sh mysqld --user=mysql --console'
    ports:
      - 127.0.0.1:${MYSQLD_PORT:-3306}:3306
    volumes:
      - ./infra/docker/mysql/conf.d:/etc/mysql/conf.d
      - ./infra/docker/mysql/mysql-init:/docker-entrypoint-initdb.d
      - mysql_data_vol:/var/lib/mysql
      - mysql_log:/var/log/mysql
    tmpfs:
      - /var/run/mysqld
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TEST_DATABASE_PREFIX=${MYSQL_TEST_DATABASE_PREFIX:-_test_}
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '1'
