#!/bin/bash
set -euo pipefail

DB="${MYSQL_DATABASE}"
USER="${MYSQL_USER}"
ROOT_PW="${MYSQL_ROOT_PASSWORD}"
USER_PW="${MYSQL_PASSWORD}"

mysql -uroot -p"${ROOT_PW}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB}\`;
CREATE USER IF NOT EXISTS '${USER}'@'%' IDENTIFIED BY '${USER_PW}';
GRANT ALL PRIVILEGES ON \`${DB}\`.* TO '${USER}'@'%';
FLUSH PRIVILEGES;
SQL
